### ISSUE TITLE
Internal calls to new Schemy() not allowing 'Schemy Settings'

### ISSUE THREAD

**Issue by JoaquinEduardoArreguez** [aeberdinelli/schemy#6]
Dentro del contructor hay varias llamadas a `new Schemy()` cuando se hacen parseos automaticos de datos, por ej para generar instancias de schemy de objetos dentro de arrays u objetos anidados donde no está la posibilidad de pasar 'settings' como `{strict:false}` para modificar el funcionamiento de esa instancia de Schemy.

Ésto pasa en todas las llamadas internas de `new Schemy()`, no se tiene en cuenta que es posible querer pasar settings como permite el constructor `constructor(schema, { strict } = {})`

Por ej dentro de async validate
```
static async validate(body, schema, includeAll = false, orderBody = false) {
		if (!(schema instanceof Schemy)) {
			schema = new Schemy(schema);
		}

		return new Promise((resolve, reject) => {
			if (schema.validate(body)) {
				return resolve(
					schema.getBody(includeAll, orderBody)
				);
			}

			return reject(schema.getValidationErrors());
		});
	}
```

O del constructor cuando una propiedad es un objeto
```
else if (typeof properties === 'object') {
						try {
							const parsed = {};
	
							if (schema[key].custom) {
								const { custom } = schema[key];
								parsed.custom = custom;
							}
	
							parsed.type = new Schemy(properties);
							parsed.required = !!properties.required;
	
							schema[key] = parsed;
						} catch (err) {
							throw `Could not parse property ${key} as schema`;
						}
					}
```

**Comment by aeberdinelli** [comment]
Hi, thank you for reporting this issue. I will tackle this and include it in the next version, looks like a quick fix

**Comment by JoaquinEduardoArreguez** [comment]
The problem was hard to explain and couldn't do it using english, sorry about that!  😮‍💨 will do my best regarding following contributions 🕺🏻

**Comment by JoaquinEduardoArreguez** [comment]
actually, it may be more difficult than expected, since the notation for describing the schema should change so you can explicitly separate the schema from the settings, so should be something like
```js
const schemaStructure = {
  schema: {
    name: String,
    address: {
      schema: {
        address1: String,
        address2: { type: String, required: false },
      },
      settings: {}, // Could be excluded if no settings, but the parser must be aware of it
    },
  },
  settings: {
    strict: true,
  },
};

const validator = new Schemy(schemaStructure);
```

**Comment by aeberdinelli** [comment]
hmm, not sure if I follow. Right now it's actually working in a similar way, you pass the settings in a different argument, in some places we could do something like:

```javascript
new Schemy(...[schema, settings]);
```

That way we are importing the settings in the instance from the current schemy instance. On the other hand, we could add an optional param to the `validate` method you are talking about, since we don't want to change how we declare the schema to prevent breaking changes. What are your thoughts?

**Comment by JoaquinEduardoArreguez** [comment]
Hi! yes, we can do 
```js
new Schemy ({...schema_object}, {...schema_settings_object})
```
But what about anidated objects that rely on auto-parse? e.g
```js
const personData = {
  name: String,
  address: {
    address1: String,
    address2: { type: String, required: false }
  }
}

const personValidator = new Schemy(personData, { strict: false })
```
Here we set `strict:false` to modify the schemy instance 'personValidator', but the constructor will also parse automatically the `address` property as another Schemy instance , lets call it `addressValidator`;
how could we apply settings to this schemy instances that are created automatically? for example if I want `personValidator` to be `strict:false` but `addressValidator` to be `strict`

At the moment, we can create every schemy instance manually and specify settings there, e.g
```js
const addressValidator = new Schemy({
  address1: String,
  address2: { type: String, required: false }
}, { strict: true })

const personData = {
  name: String,
  address: { type: addressValidator, required: true }
}

const personValidator = new Schemy(personData, { strict: false })
```

But it would be nice having some mechanism to specify settings on those anidated objects without having to create them manually.

The first approach that comes to my mind is the one that I mentioned earlier, but requires changing the way schemas are declared, eg
```js
const personSchema = {
  schema: {
    name: String,
    address: {
      schema: {
        address1: String,
        address2: { type: String, required: false }
      },
      settings: { strict: true } // Could be omited as strict:true is the default
    }
  },
  settings: { strict: false }
}

const personValidator = new Schemy(personSchema)
```

I know this is a breaking change and I don't want that either! but this example helps me explain the limitation I see about applying settings to anidated objects when relying on auto-parse;

Today I dont see this as a bug, but as a `syntactic sugar`.

If more settings become available a simple solution without requiring a breaking change could be to 'inherit' parent settings to all auto-parsed schemy instances

**Comment by aeberdinelli** [comment]
After thinking about it, I believe there's no good option to prevent breaking changes, so I think I'm closing this issue as a wont fix. However, you'll always be able to set that configuration if you create a separate schema for your parent schema property. Thanks for your ideas, I will update if any other ideas come to mind. 

Before I forget, you can always [make a plugin](https://github.com/aeberdinelli/schemy/wiki/Writing-a-plugin) for your specific use case. You can override the calling signature just as you require, using a property for settings and another one for the schema. Good luck and keep me posted if you go for that approach!

**Comment by JoaquinEduardoArreguez** [comment]
Thanks for the plugin you made for this! [I'm leaving this link here](https://github.com/aeberdinelli/schemy-child-settings) so anybody reading this issue can find the plugin
