### ISSUE TITLE
Incorrect validations when using anidated schemy instances

### ISSUE THREAD

**Issue by JoaquinEduardoArreguez** [aeberdinelli/schemy#7]
cuando se anidan instancias de schemy para poder validad objetos anidados, de la forma 
```js
it("Should pass validation with correct child schemas using strict property", function () {
    const nameSchema = new Schemy(
      {
        firstname: {
          type: String,
          required: true,
        },
        lastname: {
          type: String,
        },
      },
      { strict: false }
    );

    const personSchema = new Schemy(
      {
        name: { type: nameSchema, required: true },
        age: { type: Number, required: true },
      },
      { strict: false }
    );

    const payload = {
      name: {
        firstname: "Joaquin",
        lastname: "Arreguez",
        secondName: "Eduardo",
      },
      age: 28,
      address: "Avenida Siempre Viva 666",
    };

    const result = personSchema.validate(payload);

    expect(result).toBe(true);
  });
  ```
  
  El schema padre (personSchema) incluye como propiedad de una de sus keys otra instancia de schemy (nameSchema),
  Al llamarse el constructor en 
  ```js
  const personSchema = new Schemy(
      {
        name: { type: nameSchema, required: true },
        age: { type: Number, required: true },
      },
      { strict: false }
    );
```
El constructor invocará `new Schemy()` nuevamente sobre la propiedad `name: { type: nameSchema, required: true }` ya que `typeof nameSchema === 'object'`, haciendo que se cree una instancia de Schemy cuyo esquema es la estrutura de una instancia de Schemy (`{validationErrors: null , data... etc}`) haciendo que las validaciones fallen, ya que el schema anidado esperado no es el mismo que el logrado. Debe agregarse una guarda checkeando si `typeof nameSchema === 'object' && !(nameSchema instanceof Schemy)`

**Comment by JoaquinEduardoArreguez** [comment]
Voy a proponer un cambio agregando ésta guarda para no hacer `new Schemy()` sobre algo que ya es una instancia de `Schemy`, agregando un test para el caso concreto y modificando otro test cambiando `expect(result).toBe(jasmine.any(Array));` por `expect(result).toEqual(jasmine.any(Array));` ya que la primera forma da un error

**Comment by aeberdinelli** [comment]
I saw your PR and looks good, just requested a small indentation change. Remember you can include something like `#7` in the title of your PR and it will link it automatically to this issue, to keep track of it. Thank you for your contribution!

**Comment by aeberdinelli** [comment]
Closing with PR #8. Your solution is live in version 3.0.6, congratulations and thank you for your support!
