### ISSUE TITLE
Schemy instance persisting validation errors on succesive invocations of AWS lambda function

### ISSUE THREAD

**Issue by JoaquinEduardoArreguez** [aeberdinelli/schemy#9]
Hi again!!
I have noticed an error regarding validation errors since version `3.2.1` , when using schemy on lambda functions errors are being propagated between lambda invocations.

I am almost certain that the cause is this change here
![image](https://user-images.githubusercontent.com/11872931/133661109-a5dc4718-06a1-482c-a6ad-fb0d3b6e019b.png)

On version `3.2.0` the validationErrors array was being cleared on every invocation, now if this array comes with validation errors from a previous lambda invocation (since aws lambdas preserve all static code as long as the instance doesn't die) it doesn't get into that if statement and the validationErrors array wont be cleared

**Comment by aeberdinelli** [comment]
Hi! Thanks for reporting this. You're right, that was the issue. I published version v3.2.3 with the bugfix, please upgrade to get the fix. Thank you!

**Comment by JoaquinEduardoArreguez** [comment]
Thanks for fixing it so fast!!!
